/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as RunsIdIndexRouteImport } from './routes/runs.$id.index'
import { Route as RunsIdStakeholderRouteImport } from './routes/runs.$id.stakeholder'
import { Route as RunsIdTraceRouteImport } from './routes/runs.$id.trace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdIndexRoute = RunsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsIdRoute,
} as any)
const RunsIdStakeholderRoute = RunsIdStakeholderRouteImport.update({
  id: '/stakeholder',
  path: '/stakeholder',
  getParentRoute: () => RunsIdRoute,
} as any)
const RunsIdTraceRoute = RunsIdTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => RunsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/runs/$id': typeof RunsIdRouteWithChildren
  '/runs/$id/stakeholder': typeof RunsIdStakeholderRoute
  '/runs/$id/trace': typeof RunsIdTraceRoute
  '/runs/$id/': typeof RunsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/runs/$id/stakeholder': typeof RunsIdStakeholderRoute
  '/runs/$id/trace': typeof RunsIdTraceRoute
  '/runs/$id': typeof RunsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memory': typeof MemoryRoute
  '/runs/$id': typeof RunsIdRouteWithChildren
  '/runs/$id/stakeholder': typeof RunsIdStakeholderRoute
  '/runs/$id/trace': typeof RunsIdTraceRoute
  '/runs/$id/': typeof RunsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memory'
    | '/runs/$id'
    | '/runs/$id/stakeholder'
    | '/runs/$id/trace'
    | '/runs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/memory' | '/runs/$id/stakeholder' | '/runs/$id/trace' | '/runs/$id'
  id:
    | '__root__'
    | '/'
    | '/memory'
    | '/runs/$id'
    | '/runs/$id/stakeholder'
    | '/runs/$id/trace'
    | '/runs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoryRoute: typeof MemoryRoute
  RunsIdRoute: typeof RunsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id/': {
      id: '/runs/$id/'
      path: '/'
      fullPath: '/runs/$id/'
      preLoaderRoute: typeof RunsIdIndexRouteImport
      parentRoute: typeof RunsIdRoute
    }
    '/runs/$id/stakeholder': {
      id: '/runs/$id/stakeholder'
      path: '/stakeholder'
      fullPath: '/runs/$id/stakeholder'
      preLoaderRoute: typeof RunsIdStakeholderRouteImport
      parentRoute: typeof RunsIdRoute
    }
    '/runs/$id/trace': {
      id: '/runs/$id/trace'
      path: '/trace'
      fullPath: '/runs/$id/trace'
      preLoaderRoute: typeof RunsIdTraceRouteImport
      parentRoute: typeof RunsIdRoute
    }
  }
}

interface RunsIdRouteChildren {
  RunsIdStakeholderRoute: typeof RunsIdStakeholderRoute
  RunsIdTraceRoute: typeof RunsIdTraceRoute
  RunsIdIndexRoute: typeof RunsIdIndexRoute
}

const RunsIdRouteChildren: RunsIdRouteChildren = {
  RunsIdStakeholderRoute: RunsIdStakeholderRoute,
  RunsIdTraceRoute: RunsIdTraceRoute,
  RunsIdIndexRoute: RunsIdIndexRoute,
}

const RunsIdRouteWithChildren =
  RunsIdRoute._addFileChildren(RunsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoryRoute: MemoryRoute,
  RunsIdRoute: RunsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
